In [1]:
import pandas as pd

In [4]:
data_wiki = pd.read_csv("data/poland_cases.csv").iloc[:, [6, 9, 10]]

In [5]:
data_wiki

    Cases Recovered Deaths
0       0         0      0
1       0         0      0
2       0         0      0
3       0         0      0
4       0         0      0
..    ...       ...    ...
131   205       220      4
132   257       272      7
133   277       640     14
134   262       599      8
135   265       571     11

[136 rows x 3 columns]

In [6]:
data_wiki["Deaths"] = pd.to_numeric(data_wiki["Deaths"].str.extract(r'^(\d+)', expand=False))

In [7]:
data_wiki["Recovered"] = pd.to_numeric(data_wiki["Recovered"].str.extract(r'^(\d+)', expand=False))

In [8]:
data_wiki["Cases"] = pd.to_numeric(data_wiki["Cases"].str.extract(r'^(\d+)', expand=False))

In [67]:
def prepare_dataframe(data, n):
    new = pd.DataFrame()
    new["Cases"] = data.iloc[(n - 1):, 0].values
    new["Recovered"] = data.iloc[(n - 1):, 1].values
    new["Deaths"] = data.iloc[(n - 1):, 2].values
    for j in range(1, n):
        
        new["Cases " + str(j)+" days before"] = data.iloc[(n - j - 1):-j, 0].values
        new["Recovered " + str(j)+" days before"] = data.iloc[(n - j - 1):-j, 1].values
        new["Deaths " + str(j)+" days before"] = data.iloc[(n - j - 1):-j, 2].values
    return new

## The same but with target as a list

In [62]:
def prepare_dataframe2(data, n):
    new = pd.DataFrame()
    targetColumn = []
    for row in range(n-1,len(data.index)):
        targetColumn.append([data.iloc[row, 0], data.iloc[row, 1],data.iloc[row, 2]])
    new['target'] = targetColumn
    
    for j in range(1, n):
        new["Cases " + str(j)+" days before"] = data.iloc[(n - j - 1):-j, 0].values
        new["Recovered " + str(j)+" days before"] = data.iloc[(n - j - 1):-j, 1].values
        new["Deaths " + str(j)+" days before"] = data.iloc[(n - j - 1):-j, 2].values
    
    return new

In [22]:
data = prepare_dataframe(data_wiki, 6)

In [65]:
data2 = prepare_dataframe2(data_wiki,8)

In [66]:
data2

,target,Cases 1 days before,Recovered 1 days before,Deaths 1 days before,Cases 2 days before,Recovered 2 days before,Deaths 2 days before,Cases 3 days before,Recovered 3 days before,Deaths 3 days before,...,Deaths 4 days before,Cases 5 days before,Recovered 5 days before,Deaths 5 days before,Cases 6 days before,Recovered 6 days before,Deaths 6 days before,Cases 7 days before,Recovered 7 days before,Deaths 7 days before
0,"[1, 0, 0]",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,"[0, 0, 0]",1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,"[4, 0, 0]",0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,"[1, 0, 0]",4,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,"[5, 0, 0]",1,0,0,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,"[205, 220, 4]",231,619,5,314,476,5,259,442,15,...,15,382,510,14,239,384,19,247,349,6
125,"[257, 272, 7]",205,220,4,231,619,5,314,476,5,...,15,371,418,15,382,510,14,239,384,19
126,"[277, 640, 14]",257,272,7,205,220,4,231,619,5,...,5,259,442,15,371,418,15,382,510,14
127,"[262, 599, 8]",277,640,14,257,272,7,205,220,4,...,5,314,476,5,259,442,15,371,418,15
128,"[265, 571, 11]",262,599,8,277,640,14,257,272,7,...,4,231,619,5,314,476,5,259,442,15

In [72]:
data2.to_csv("data/data_processed.csv", index=False)

In [17]:
def tt_split(X, Y , test_size = 0.2):
    threshold = int(len(X.index)*(1-test_size))
    X_train = X.iloc[:threshold,]
    Y_train = Y.iloc[:threshold,]
    X_test = X.iloc[threshold+1:,]
    Y_test = Y.iloc[threshold+1:,]
    return X_train, X_test, y_train, y_test

In [18]:
X_train, X_test, y_train, y_test = tt_split(data.drop("target", axis = 1), data["target"], test_size=0.1)